### ISSUE TITLE
Paper referred 

### ISSUE THREAD

**Issue by Pavanxr98** [GutlapalliNikhil/3D-Mapping-Using-2D-LiDAR-ROS#3]
Can u share us the link of the Reference paper related to this

**Comment by GutlapalliNikhil** [comment]
Hi. Please checkout this paper: https://www.researchgate.net/publication/368572857_2D-3D_hybrid_mapping_for_path_planning_in_autonomous_robots. It's bit related and high level to this project. Thanks
